#!/usr/bin/env python3
"""
Generated by LLM, adjusted by human
Combine entries from two JSON result files by output_number.

- If one entry passes and the other fails, use the passing entry entirely but append the stderrs from teh failing entry
- Standard errors are appended (with separator) when merging
- Scaling runtimes: minimum value at each processor count is selected
- Other runtimes: minimum value is selected
- If only one JSON has a value, that value is used
- the max status between the two are selected 

NOTE: if both outputs among the two json files fail, the errors get appended, so error analysis would be a sum 

"""

"""
COMMANDS: 
python combine_runs_hpx.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/gpt-5.3-codex/results_1.5.1.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/gpt-5.3-codex/results_1.10.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/gpt-5.3-codex/results.json
python combine_runs_hpx.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/opus/results_1.5.1.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/opus/results_1.10.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/opus/results.json
python combine_runs_hpx.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/oss/results_1.5.1.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/oss/results_1.10.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/oss/results.json
python combine_runs_hpx.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/glm/results_1.5.1.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/glm/results_1.10.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/glm/results.json
python combine_runs_hpx.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/minimax/results_1.5.1.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/minimax/results_1.10.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/minimax/results.json
python combine_runs_hpx.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/magicoder/results_1.5.1.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/magicoder/results_1.10.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/magicoder/results.json
python combine_runs_hpx.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/hpccoder/results_1.5.1.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/hpccoder/results_1.10.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/hpccoder/results.json

"""

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


def get_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "json1",
        type=str,
        help="First JSON file path.",
    )
    parser.add_argument(
        "json2",
        type=str,
        help="Second JSON file path.",
    )
    parser.add_argument(
        "-o", "--output",
        type=str,
        default="results.json",
        help="Output JSON file path (default: results.json).",
    )
    parser.add_argument(
        "--key",
        type=str,
        nargs="+",
        default=["app", "llm_name", "output_number"],
        help="Keys to use for matching entries (default: app llm_name output_number).",
    )
    parser.add_argument(
        "--separator",
        type=str,
        default="\n\n",
        help="Separator for appending stderr fields.",
    )
    return parser.parse_args()


def make_key(entry: Dict[str, Any], key_fields: List[str]) -> tuple:
    """Create a hashable key from the specified fields."""
    return tuple(entry.get(field) for field in key_fields)


def did_entry_pass(entry: Dict[str, Any], use_code_only: bool = False) -> bool:
    """
    returns True only if all outputs have status "PASS"  for code or non code only config
    """
    if use_code_only:
        overall_status = entry.get("code_only_overall_status", {})
    else:
        overall_status = entry.get("overall_status", {})
    
    if not overall_status:
        return False
    
    if isinstance(overall_status, dict):
        return all(status == "PASS" for status in overall_status.values())
    
    return False


def get_pass_status(entry: Dict[str, Any]) -> Tuple[bool, bool]:
    """
    Get pass status for both regular and code_only validation.
    
    Returns (regular_passed, code_only_passed)
    """
    regular_passed = did_entry_pass(entry, use_code_only=False)
    code_only_passed = did_entry_pass(entry, use_code_only=True)
    return regular_passed, code_only_passed


def count_passes(entry: Dict[str, Any]) -> int:
    """
    Count how many validations passed (0, 1, or 2).
    """
    regular, code_only = get_pass_status(entry)
    return int(regular) + int(code_only)


def append_stderr(val1: Any, val2: Any, separator: str) -> Any:
    """Append stderr values, handling strings and lists."""
    if val1 is None or val1 == "":
        return val2
    if val2 is None or val2 == "":
        return val1
    
    # Handle lists (like run_stderrs)
    if isinstance(val1, list) and isinstance(val2, list):
        combined = []
        max_len = max(len(val1), len(val2))
        for i in range(max_len):
            v1 = val1[i] if i < len(val1) else ""
            v2 = val2[i] if i < len(val2) else ""
            if v1 and v2:
                combined.append(f"{v1}{separator}{v2}")
            else:
                combined.append(v1 or v2)
        return combined
    
    # Handle strings
    if isinstance(val1, str) and isinstance(val2, str):
        if val1 and val2:
            return f"{val1}{separator}{val2}"
        return val1 or val2
    
    # Fallback: return first non-empty
    return val1 if val1 else val2

def append_stderr_because_one_successful(
    passed: Dict[str, Any],
    failed: Dict[str, Any],
    separator: str
) -> Dict[str, Any]:
    result = dict(passed)
    
    # Fields to append (stderr fields)
    stderr_fields = [
        "build_stderr",
        "run_stderrs",
        "code_only_build_stderr",
        "code_only_run_stderrs",
    ]
    
    for field in stderr_fields:
        if field in passed or field in failed:
            result[field] = append_stderr(
                passed.get(field),
                failed.get(field),
                separator
            )
    
    return result

STATUS_PRIORITY = { #MISSING DOESN"T COUNT TOWARDS RUN@K, so it is considered teh same level as RUNTIME_FAIL
    "INCORRECT_MODEL": 0,
    "BUILD_FAIL": 1,
    "RUNTIME_FAIL": 2,
    "MISSING": 2,        
    "VALIDATION_FAIL": 3,  
    "PASS": 4,
}


def status_priority(status):
    return STATUS_PRIORITY.get(status)
    
def select_better_status(status1: str, status2: str) -> str:
    """
    Select the higher prio status, or either if both the same
    """
    if (status1 == "PASS") or (status2 == "PASS"):
        return "PASS"
    
    priority1 = status_priority(status1)
    priority2 = status_priority(status2)
    
    if priority1 >= priority2:
        return status1
    else:
        return status2
    
def merge_statuses(status1, status2):  #dict of merged better statuses (only really relevant for asyncstm, as otherwise you can just call select_better_status)
    merged_statuses = {}
    for key in status1.keys():
        s1 = status1.get(key) 
        s2 = status2.get(key) 
        merged_statuses[key] = select_better_status(s1, s2)
    return merged_statuses
    
def select_min_runtime(val1: Any, val2: Any) -> Any:
    """Select the minimum runtime value, handling -1 as invalid."""
    if val1 is None:
        return val2
    if val2 is None:
        return val1
    
    # Handle dict runtimes (like AsyncSTM per-file runtimes)
    if isinstance(val1, dict) and isinstance(val2, dict):
        combined = {}
        all_keys = set(val1.keys()) | set(val2.keys())
        for key in all_keys:
            v1 = val1.get(key, -1)
            v2 = val2.get(key, -1)
            if v1 < 0 and v2 < 0:
                combined[key] = -1
            elif v1 < 0:
                combined[key] = v2
            elif v2 < 0:
                combined[key] = v1
            else:
                combined[key] = min(v1, v2)
        return combined
    
    # Handle scalar runtimes
    if isinstance(val1, (int, float)) and isinstance(val2, (int, float)):
        # -1 means invalid/failed
        if val1 < 0 and val2 < 0:
            return -1
        if val1 < 0:
            return val2
        if val2 < 0:
            return val1
        return min(val1, val2)
    
    # Fallback
    return val1 if val1 is not None else val2


def select_min_scaling_runtimes(list1: Optional[List], list2: Optional[List]) -> Optional[List]:
    """Select minimum runtime at each processor count position."""
    if list1 is None:
        return list2
    if list2 is None:
        return list1
    
    if not isinstance(list1, list) or not isinstance(list2, list):
        return list1 if list1 is not None else list2
    
    # Ensure same length
    if len(list1) != len(list2):
        print(f"Warning: scaling_runtimes have different lengths ({len(list1)} vs {len(list2)})")
        # Pad shorter list with None
        max_len = max(len(list1), len(list2))
        list1 = list1 + [None] * (max_len - len(list1))
        list2 = list2 + [None] * (max_len - len(list2))
    
    combined = []
    for v1, v2 in zip(list1, list2):
        if v1 is None or (isinstance(v1, (int, float)) and v1 < 0):
            combined.append(v2)
        elif v2 is None or (isinstance(v2, (int, float)) and v2 < 0):
            combined.append(v1)
        else:
            combined.append(min(v1, v2))
    
    return combined


def merge_entries(entry1: Dict[str, Any], entry2: Dict[str, Any], separator: str) -> Dict[str, Any]:
    """Merge two entries, combining stderr and selecting min runtimes."""
    # Start with a copy of entry1
    merged = dict(entry1)
    
    # Fields to append (stderr fields)
    stderr_fields = [
        "build_stderr",
        "run_stderrs",
        "code_only_build_stderr",
        "code_only_run_stderrs",
    ]
    
    # Fields to select minimum runtime
    runtime_fields = [
        "runtime",
        "code_only_runtime",
    ]
    
    # Process stderr fields - append to each other (so error analysis is sum of errors between two versions assuming they both fail)
    for field in stderr_fields:
        if field in entry1 or field in entry2:
            merged[field] = append_stderr(
                entry1.get(field),
                entry2.get(field),
                separator
            )
    
    # Process runtime fields - select minimum
    for field in runtime_fields:
        if field in entry1 or field in entry2:
            merged[field] = select_min_runtime(
                entry1.get(field),
                entry2.get(field)
            )
    #merge statuses
    merged["code_only_overall_status"] = merge_statuses(entry1.get("code_only_overall_status"),entry2.get("code_only_overall_status"))
    merged["code_only_overall_status"] = merge_statuses(entry1.get("code_only_overall_status"),entry2.get("code_only_overall_status"))
    
    # Process scaling_runtimes - select minimum at each position
    if "scaling_runtimes" in entry1 or "scaling_runtimes" in entry2:
        merged["scaling_runtimes"] = select_min_scaling_runtimes(
            entry1.get("scaling_runtimes"),
            entry2.get("scaling_runtimes")
        )
    
    # For scaling_performed, set True if either is True
    if entry1.get("scaling_performed") or entry2.get("scaling_performed"):
        merged["scaling_performed"] = True
    
    # For scaling_success, set True only if both are True (or only one exists and it's True)
    sp1 = entry1.get("scaling_success")
    sp2 = entry2.get("scaling_success")
    if sp1 is not None and sp2 is not None:
        merged["scaling_success"] = sp1 and sp2
    else:
        merged["scaling_success"] = sp1 if sp1 is not None else sp2
    
    # Use scaling_processors from whichever has it (should be the same)
    if entry1.get("scaling_processors") is None and entry2.get("scaling_processors") is not None:
        merged["scaling_processors"] = entry2["scaling_processors"]
    
    # Use scaling_returncodes - prefer all zeros
    rc1 = entry1.get("scaling_returncodes")
    rc2 = entry2.get("scaling_returncodes")
    if rc1 is not None and rc2 is not None:
        # Select the one with fewer non-zero return codes
        if sum(1 for r in rc1 if r != 0) <= sum(1 for r in rc2 if r != 0):
            merged["scaling_returncodes"] = rc1
        else:
            merged["scaling_returncodes"] = rc2
    elif rc2 is not None:
        merged["scaling_returncodes"] = rc2
    
    return merged


def select_or_merge_entries(
    entry1: Dict[str, Any],
    entry2: Dict[str, Any],
    separator: str
) -> Tuple[Dict[str, Any], str]:
    """
    Decide whether to select one entry or merge both.
    
    Logic:
    - If one passes and the other fails, use the passing entry entirely
    - If both pass or both fail, merge them
    
    Returns (result_entry, decision_reason)
    """
    passes1 = count_passes(entry1)
    passes2 = count_passes(entry2)
    
    reg1, co1 = get_pass_status(entry1)
    reg2, co2 = get_pass_status(entry2)
    
    # Case 1: entry1 has more passes -> use entry1
    if passes1 > passes2:
        reason = f"entry1 has more passes ({passes1} vs {passes2})"
        result = append_stderr_because_one_successful(entry1, entry2, separator)
        result["overall_status"] = merge_statuses(entry1.get("overall_status"), entry2.get("overall_status"))
        result["code_only_overall_status"] = merge_statuses(entry1.get("code_only_overall_status"), entry2.get("code_only_overall_status") )
        return result, reason
        #return dict(entry1), reason
    
    # Case 2: entry2 has more passes -> use entry2
    if passes2 > passes1:
        reason = f"entry2 has more passes ({passes2} vs {passes1})"
        result = append_stderr_because_one_successful(entry2, entry1, separator) 
        result["overall_status"] = merge_statuses(entry1.get("overall_status"), entry2.get("overall_status"))
        result["code_only_overall_status"] = merge_statuses(entry1.get("code_only_overall_status"), entry2.get("code_only_overall_status") )
        return result, reason
    
    # Case 3: Same number of passes
    # Sub-case: Both have 0 passes -> merge (combine errors)
    if passes1 == 0 and passes2 == 0:
        reason = "both failed, merging stderr"
        return merge_entries(entry1, entry2, separator), reason
    
    # Sub-case: Both have same passes (1 or 2) -> merge (combine for min runtimes)
    # But check if they pass on different validations
    if passes1 == passes2:
        # If they pass on the same validations, merge for min runtimes
        if reg1 == reg2 and co1 == co2:
            reason = f"both have {passes1} passes on same validations, merging for min runtimes"
            return merge_entries(entry1, entry2, separator), reason
        
        # If they pass on different validations, still merge but note it
        reason = f"both have {passes1} passes but on different validations, merging"
        return merge_entries(entry1, entry2, separator), reason
    
    # Fallback: merge
    reason = "fallback merge"
    return merge_entries(entry1, entry2, separator), reason


def combine_json_files(
    json1_path: str,
    json2_path: str,
    key_fields: List[str],
    separator: str
) -> List[Dict[str, Any]]:
    """Combine entries from two JSON files."""
    
    # Load both JSON files
    with open(json1_path, "r", encoding="utf-8") as f:
        data1 = json.load(f)
    
    with open(json2_path, "r", encoding="utf-8") as f:
        data2 = json.load(f)
    
    if not isinstance(data1, list):
        data1 = [data1]
    if not isinstance(data2, list):
        data2 = [data2]
    
    print(f"Loaded {len(data1)} entries from {json1_path}")
    print(f"Loaded {len(data2)} entries from {json2_path}")
    
    # Index entries from json2 by key
    json2_index: Dict[tuple, Dict[str, Any]] = {}
    for entry in data2:
        key = make_key(entry, key_fields)
        json2_index[key] = entry
    
    # Process entries from json1, merging with json2 if matched
    combined = []
    matched_keys = set()
    
    stats = {
        "used_entry1": 0,
        "used_entry2": 0,
        "merged": 0,
    }
    
    for entry1 in data1:
        key = make_key(entry1, key_fields)
        
        if key in json2_index:
            # Decide whether to select or merge
            entry2 = json2_index[key]
            result, reason = select_or_merge_entries(entry1, entry2, separator)
            combined.append(result)
            matched_keys.add(key)
            
            # Track stats
            if "entry1" in reason and "more passes" in reason:
                stats["used_entry1"] += 1
            elif "entry2" in reason and "more passes" in reason:
                stats["used_entry2"] += 1
            else:
                stats["merged"] += 1
            
            print(f"  {key}: {reason}")
        else:
            # No match, keep entry1 as-is
            combined.append(entry1)
    
    # Add unmatched entries from json2
    unmatched_from_json2 = 0
    for entry2 in data2:
        key = make_key(entry2, key_fields)
        if key not in matched_keys:
            combined.append(entry2)
            unmatched_from_json2 += 1
            print(f"  Unmatched from json2: {key}")
    
    print(f"\n{'='*60}")
    print(f"SUMMARY")
    print(f"{'='*60}")
    print(f"Total combined entries: {len(combined)}")
    print(f"  Matched entries: {len(matched_keys)}")
    print(f"    - Used entry1 (more passes): {stats['used_entry1']}")
    print(f"    - Used entry2 (more passes): {stats['used_entry2']}")
    print(f"    - Merged (same pass count): {stats['merged']}")
    print(f"  From json1 only: {len(data1) - len(matched_keys)}")
    print(f"  From json2 only: {unmatched_from_json2}")
    
    return combined


def main() -> None:
    args = get_args()
    
    json1_path = Path(args.json1).resolve()
    json2_path = Path(args.json2).resolve()
    
    if not json1_path.is_file():
        raise SystemExit(f"Error: {json1_path} is not a file.")
    if not json2_path.is_file():
        raise SystemExit(f"Error: {json2_path} is not a file.")
    
    combined = combine_json_files(
        str(json1_path),
        str(json2_path),
        args.key,
        args.separator
    )
    
    output_path = Path(args.output)
    with output_path.open("w", encoding="utf-8") as f:
        json.dump(combined, f, indent=2)
    
    print(f"\nWrote combined results to {output_path}")


if __name__ == "__main__":
    main()