#!/usr/bin/env python3
"""
Generated by LLM, adjusted by human 
Compute build@k, pass@k, and run@k metrics from a single JSON results file."""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd
from math import comb

ALL_STATUSES = [
    "INCORRECT_MODEL",
    "BUILD_FAIL",
    "RUNTIME_FAIL",
    "MISSING",
    "VALIDATION_FAIL",
    "PASS",
]

#usage examples
# python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/opus/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/opus/opus.csv
#python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/gpt-5.3-codex/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/gpt-5.3-codex/
#python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/gpt-5.3-codex/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/gpt-5.3-codex/gpt-5.3-codex.csv

"""
#heapify
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/gpt-5.3-codex/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/gpt-5.3-codex/gpt-5.3-codex.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/opus/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/opus/opus.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/glm/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/glm/glm.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/oss/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/oss/oss.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/minimax/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/minimax/minimax.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/hpccoder/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/hpccoder/hpccoder.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/magicoder/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/magicoder/magicoder.csv

#AsyncSTM (out of 60 for code-only and repo)
python compute_\@k_asyncstm.py /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/gpt-5.3-codex/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/gpt-5.3-codex/gpt-5.3-codex.csv
python compute_\@k_asyncstm.py /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/opus/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/opus/opus.csv
python compute_\@k_asyncstm.py /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/glm/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/glm/glm.csv
python compute_\@k_asyncstm.py /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/oss/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/oss/oss.csv
python compute_\@k_asyncstm.py /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/minimax/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/minimax/minimax.csv
python compute_\@k_asyncstm.py /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/hpccoder/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/hpccoder/hpccoder.csv
python compute_\@k_asyncstm.py /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/magicoder/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/magicoder/magicoder.csv


#Barnes_Hut (TODO COMBINE 1.5.1 and 1.10.0)
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/gpt-5.3-codex/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/gpt-5.3-codex/gpt-5.3-codex.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/opus/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/opus/opus.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/glm/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/glm/glm.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/oss/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/oss/oss.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/minimax/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/minimax/minimax.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/hpccoder/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/hpccoder/hpccoder.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/magicoder/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/magicoder/magicoder.csv

#osc chain 1d
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/gpt-5.3-codex/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/gpt-5.3-codex/gpt-5.3-codex.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/opus/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/opus/opus.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/glm/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/glm/glm.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/oss/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/oss/oss.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/minimax/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/minimax/minimax.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/hpccoder/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/hpccoder/hpccoder.csv
python compute_\@k.py /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/magicoder/results.json -o /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/magicoder/magicoder.csv

"""
def get_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "input_file",
        type=str,
        help="JSON file containing a list of result objects.",
    )
    parser.add_argument(
        "-k",
        "--k",
        type=int,
        nargs="+",
        default=[1, 3, 5],
        help="K values for build@k, pass@k, run@k (default: 1 3 5).",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        default=None,
        help="Output CSV file path (default: prints to stdout).",
    )
    parser.add_argument(
        "--group-by",
        type=str,
        nargs="+",
        default=["llm_name", "source_model", "dest_model"],
        help="Fields to group by when computing metrics (default: llm_name source_model dest_model).",
    )
    return parser.parse_args()

def nCr(n: int, r: int) -> int:
    if n < r:
        return 1
    return comb(n, r)


def _passk(num_samples: int, num_correct: int, k: int) -> float:
    """Unbiased estimator of pass@k."""
    if num_samples < k:
        if num_samples == 0:
            return 0.0
        return float(num_correct > 0)
    if num_correct == 0:
        return 0.0
    if num_samples - num_correct < k:
        return 1.0
    return 1.0 - np.prod(1.0 - k / np.arange(num_samples - num_correct + 1, num_samples + 1))



def derive_flags(status: str) -> Dict[str, bool]:
    """
    From a status string, derive the three success flags:
      - did_build: not BUILD_FAIL and not INCORRECT_MODEL -> build@k
      - did_run:   VALIDATION_FAIL or PASS (MISSING COUNTS AGAINST IT) -> run@k
      - did_pass:  only PASS -> pass@k
    """
    return {
        "did_build": status not in ("BUILD_FAIL", "INCORRECT_MODEL"),
        "did_run": status in ("VALIDATION_FAIL", "PASS"),
        "did_pass": status == "PASS",
    }

def get_status_from_dict(status_dict):
    """ extract status from dict and represent as number (as multiple file names make key value pairs in the status list)"""
    if not status_dict:
        return "MISSING"

    priority = {
        "INCORRECT_MODEL": 0,
        "BUILD_FAIL": 1,
        "RUNTIME_FAIL": 2,
        "MISSING": 3,
        "VALIDATION_FAIL": 4,
        "PASS": 5,
    }
    #print(type(status_dict))
    #print("VALS", status_dict.values())
    return min(status_dict.values(), key=lambda x: priority[x])


def json_to_dataframe(data: List[Dict[str, Any]]) -> pd.DataFrame:
    """Convert JSON entries to a DataFrame with derived status columns for both
    regular (overall_status) and code_only (code_only_overall_status) and  both dfs."""
    regular_rows = [] 
    code_only_rows = []
    for entry in data:
        base_meta = {
            "app": entry.get("app", "unknown"),
            "prompt_strategy": entry.get("prompt_strategy", "unknown"),
            "llm_name": entry.get("llm_name", "unknown"),
            "source_model": entry.get("source_model", "unknown"),
            "dest_model": entry.get("dest_model", "unknown"),
            "output_number": entry.get("output_number", 0),
        }

        # regular pipeline
        reg_status_dict = entry.get("overall_status", {})
        #print("DICT", reg_status_dict, type(reg_status_dict))
        co_status_dict = entry.get("code_only_overall_status", {}) 
        reg_status = get_status_from_dict(reg_status_dict)
        reg_flags = derive_flags(reg_status)
        regular_rows.append({**base_meta, "status": reg_status, **reg_flags})

        #code_only pipeline 
        co_status_dict = entry.get("code_only_overall_status", {})
        co_status = get_status_from_dict(co_status_dict)
        co_flags = derive_flags(co_status)
        code_only_rows.append({**base_meta, "status": co_status, **co_flags})
    df_regular = pd.DataFrame(regular_rows)
    df_code_only = pd.DataFrame(code_only_rows) 
    df_both = pd.concat([df_regular, df_code_only], ignore_index =True)
    return df_regular, df_code_only, df_both


# def compute_metric_k(
#     df: pd.DataFrame,
#     success_col: str,
#     metric_name: str,
#     k: int,
#     group_cols: List[str],
# ) -> pd.DataFrame:
#     """
#     Compute metric@k for a given success column.
#     Groups by (app, *group_cols), computes pass@k per app, then averages across apps.
#     """
#     agg_cols = ["app"] + group_cols
#     agg = df.groupby(agg_cols).agg(
#         num_samples=(success_col, "count"),
#         num_correct=(success_col, "sum"),
#     ).reset_index()

#     col_name = f"{metric_name}@{k}"
#     agg[col_name] = agg.apply(
#         lambda x: _passk(int(x["num_samples"]), int(x["num_correct"]), k), axis=1
#     )

#     result = agg.groupby(group_cols).agg(
#         **{
#             col_name: (col_name, "mean"),
#             "num_apps": ("app", "nunique"),
#             "total_samples": ("num_samples", "sum"),
#         }
#     ).reset_index()

#     return result

def compute_all_metrics(
    df: pd.DataFrame,
    k_values: List[int],
    group_cols: List[str],
) -> pd.DataFrame:
    """Compute build@k, run@k, and pass@k for both regular and code_only pipelines."""

    status_counts = df.groupby(group_cols + ["status"]).size().unstack(fill_value=0).reset_index()
    status_counts.columns.name = None
    
    for s in ALL_STATUSES:
        if s not in status_counts.columns:
            status_counts[s] = 0
    #get counts for each status
    status_counts["total_samples"] = status_counts[ALL_STATUSES].sum(axis=1)
    
    #only one app, so just an app col, but need to reintroduce group_cols for later grouping
    app_col =  ["app"] + group_cols
    agg_df = df.groupby(app_col).agg(
        num_samples=("status", "count"),
        num_build=("did_build", "sum"),
        num_run=("did_run", "sum"),
        num_pass=("did_pass", "sum"),
    ).reset_index()
    
    for k in k_values:
        agg_df[f"build@{k}"] = agg_df.apply(lambda x: _passk(x["num_samples"], x["num_build"], k), axis=1)
        agg_df[f"run@{k}"]   = agg_df.apply(lambda x: _passk(x["num_samples"], x["num_run"], k), axis=1)
        agg_df[f"pass@{k}"]  = agg_df.apply(lambda x: _passk(x["num_samples"], x["num_pass"], k), axis=1)
        
    metric_cols = [c for c in agg_df.columns if "@" in c]
    # rads as build@k, run@k, pass@k order
    order_map = {"build": 0, "run": 1, "pass": 2}
    metric_cols = sorted(metric_cols, key=lambda x: (order_map.get(x.split("@")[0], 99), int(x.split("@")[1])))

    agg_dict = {metric: (metric, "mean") for metric in metric_cols} 
    agg_dict["apps"] = ("app", "nunique")
    
    metrics_df = agg_df.groupby(group_cols).agg(**agg_dict).reset_index()

    # merge status counts and metrics together
    result = pd.merge(status_counts, metrics_df, on=group_cols, how="outer")

    #
    ordered_cols = group_cols + ["apps", "total_samples"] + ALL_STATUSES + metric_cols
    ordered_cols = [c for c in ordered_cols if c in result.columns]

    return result[ordered_cols]
        


def main() -> None:
    args = get_args()
    input_file = Path(args.input_file).resolve()

    if not input_file.is_file():
        raise SystemExit(f"Error: {input_file} is not a file.")

    with input_file.open("r") as fh:
        data = json.load(fh)

    if not isinstance(data, list):
        raise SystemExit("Error: JSON file must contain a list of result objects.")

    if not data:
        raise SystemExit("Error: JSON file contains no entries.")

    print(f"Loaded {len(data)} entries from {input_file}")

    # Process JSON into structured standard pandas DataFrames
    df_reg, df_co, df_comb = json_to_dataframe(data)

    # Validate group-by columns exist
    for col in args.group_by:
        if col not in df_reg.columns:
            raise SystemExit(f"Error: group-by column '{col}' not found. Available: {list(df_reg.columns)}")

    # Compute merged metrics for each pipeline
    res_reg = compute_all_metrics(df_reg, args.k, args.group_by)
    res_co = compute_all_metrics(df_co, args.k, args.group_by)
    res_comb = compute_all_metrics(df_comb, args.k, args.group_by)

    # Display Results
    print("\n=== Regular Pipeline ===")
    print(res_reg.to_string(index=False))

    print("\n=== Code-Only Pipeline ===")
    print(res_co.to_string(index=False))

    print("\n=== Combined (Union Pool) Pipeline ===")
    print(res_comb.to_string(index=False))

    # Output CSVs
    if args.output:
        base_path = Path(args.output)
        stem = base_path.stem
        ext = base_path.suffix if base_path.suffix else ".csv"
        
        path_reg = base_path.with_name(f"{stem}_regular{ext}")
        path_co = base_path.with_name(f"{stem}_code_only{ext}")
        path_comb = base_path.with_name(f"{stem}_combined{ext}")

        res_reg.to_csv(path_reg, index=False)
        res_co.to_csv(path_co, index=False)
        res_comb.to_csv(path_comb, index=False)

        print(f"\nWrote CSVs to {base_path.parent}/")
        print(f"  - {path_reg.name}")
        print(f"  - {path_co.name}")
        print(f"  - {path_comb.name}")


if __name__ == "__main__":
    main()