#!/usr/bin/env python3
"""
Parse and categorize compilation and runtime errors from validation results (COMBINED ERROR COUNTS)
Combines build_stderr and code_only_build_stderr; run_stderrs and code_only_run_stderrs.(no code-only separate analysis)
Ignores warnings and notes; focuses on errors only (all those CMakeLists warnings shouldn't be here)
Base code generated by AI, adjusted by human (me)
"""

import json
import sys
import os
import re
from collections import defaultdict
from typing import Dict, List, Tuple, Set
import csv

"""
#ODEINT
python error_extraction.py osc_chain_1d/minimax/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/minimax/errors.csv
python error_extraction.py osc_chain_1d/glm/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/glm/errors.csv
python error_extraction.py osc_chain_1d/oss/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/oss/errors.csv
python error_extraction.py osc_chain_1d/magicoder/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/magicoder/errors.csv
python error_extraction.py osc_chain_1d/hpccoder/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/hpccoder/errors.csv
python error_extraction.py osc_chain_1d/gpt-5.3-codex/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/gpt-5.3-codex/errors.csv
python error_extraction.py osc_chain_1d/opus/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/osc_chain_1d/opus/errors.csv

#ASYNCSTM
python error_extraction.py AsyncSTM/minimax/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/minimax/errors.csv
python error_extraction.py AsyncSTM/glm/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/glm/errors.csv
python error_extraction.py AsyncSTM/oss/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/oss/errors.csv
python error_extraction.py AsyncSTM/magicoder/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/magicoder/errors.csv
python error_extraction.py AsyncSTM/hpccoder/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/hpccoder/errors.csv
python error_extraction.py AsyncSTM/gpt-5.3-codex/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/gpt-5.3-codex/errors.csv
python error_extraction.py AsyncSTM/opus/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/AsyncSTM/opus/errors.csv

#HEAPIFY
python error_extraction.py heapify/minimax/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/minimax/errors.csv
python error_extraction.py heapify/glm/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/glm/errors.csv
python error_extraction.py heapify/oss/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/oss/errors.csv
python error_extraction.py heapify/magicoder/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/magicoder/errors.csv
python error_extraction.py heapify/hpccoder/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/hpccoder/errors.csv
python error_extraction.py heapify/gpt-5.3-codex/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/gpt-5.3-codex/errors.csv
python error_extraction.py heapify/opus/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/heapify/opus/errors.csv


#BARNES_HUT
python error_extraction.py Barnes_Hut/minimax/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/minimax/errors.csv
python error_extraction.py Barnes_Hut/glm/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/glm/errors.csv
python error_extraction.py Barnes_Hut/oss/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/oss/errors.csv
python error_extraction.py Barnes_Hut/magicoder/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/magicoder/errors.csv
python error_extraction.py Barnes_Hut/hpccoder/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/hpccoder/errors.csv
python error_extraction.py Barnes_Hut/gpt-5.3-codex/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/gpt-5.3-codex/errors.csv
python error_extraction.py Barnes_Hut/opus/results.json /Users/robsonlab/scratch/hpx_to_legion_repo/Barnes_Hut/opus/errors.csv

"""

# ============================================================================
# ERROR CATEGORIES AND PATTERNS
# ============================================================================

ERROR_CATEGORIES = {
    # boost-specific errors
    "Boost_Error": {
        "patterns": [
            r"is not a member of .*boost::",
            r"boost::.*is not a member",
            r"error.*boost::serialization",
            r"error.*boost::numeric",
            r"Boost.Config"
        ],
        "description": "Boost version incompatibility (not LLM fault)",
    },
    "Syntax_Error": {
        "patterns": [ #combinations of malformed source and Legion API misuse
            r"stray .* in program",
            r"extended character",
            r"unterminated",
            r"expected .* at end of input",
            r"expected .* at end of",
            r"expected primary-expression",
            r"expected.*before.*token",
            r"is not captured", #lambda func issues
            r"expected.*before",
            r"missing.*before",
            r"promise.set_exception.*", #promise not captured
            r"use of deleted function",
            r"found .* in nested-name-specifier",
            r"has no member named",
            r"is not a member of",
            r"no type named.*in namespace",
            r"forming pointer",
            r"request for member",
            r"no longer supported",
            r"does not have any field",
            r"No such file or directory",
            r"is not a class, namespace, or enumeration",
            r"not in a namespace",
            r"is not a template",
            r"is not a class",
            r"not in namespace",
            r"not a namespace-name",
            r"not in class",
            r"must be a.*function",
            r"non-static data member",
            r"is not a.*member of", 
            r"cannot be used as a function",
            r"assignment of.*location", 
            
        ],
        "description": "Malformed source (missing semi-colon) or Legion/C++ misuse organization wise",
    },
    # silly errors usually tied to gneration like stray code block artefacts 
    # "Malformed_Source": {
    #     "patterns": [
    #         r"stray .* in program",
    #         r"extended character",
    #         r"unterminated",
    #         r"expected .* at end of input",
    #         r"expected .* at end of",
    #         r"expected primary-expression",
    #         r"expected.*before.*token",
    #         r"expected.*before",
    #         r"missing.*before",
    #         r"qualified-id in declaration before",
    #         r"found .* in nested-name-specifier",
    #     ],
    #     "description": "Unparseable source: stray characters, truncation, structural syntax errors",
    # },

    # Legion or target-language specific errors (though it is sort of hard to target) 
    # TODO RESTRUCTURE AS NOT TOO SURE ABOUT THIS GROUPING  
    # "API_Misuse": {
    #     "patterns": [
    #         r"has no member named",
    #         r"is not a member of",
    #         r"was not declared in this scope",
    #         r"has not been declared",
    #         r"no type named.*in namespace",
    #         r"No such file or directory",
    #         r"is not a class, namespace, or enumeration",
    #         r"does not name a type",
    #         r"is not a template",
    #         r"is not a type",
    #         r"is not a class",
    #         r"incomplete type",
    #     ],
    #     "description": "Used nonexistent or wrong API, member, type, or include",
    # },
    # type errors mostly conversions
    "Type_Error": {
        "patterns": [
            r"invalid initialization",
            r"cannot convert",
            r"could not convert",
            r"invalid conversion",
            r"conversion from",
            r"converting function",
            r"is ambiguous",
            r"no match for",
            r"typedef declared",
            r"does not name a type",
            r"canont bind",
            r"no matching function",
            r"converting to",
            r"type/value mismatch",
            r"is not a type",
            r"cannot bind.*of type",
            r"template argument",
            r"invalid types.*for array subscript",
            r"was not declared in this scope",
            r"has not been declared",
            r"types may not be defined",
            r"may not appear in this context",
            r"incomplete type",
            r"not in type",
            r"no type named",
            r"unable to find.*operator",
            r"invalid operands of types", 
            r"may not appear in a using-declaration",
            r"invalid.*from type"
        ],
        "description": "Correct names but wrong types or conversion errors",
    },

    # incorrect use of C++ concepts in general, ie using functions that are duplicated or calling with issues with arguments
    "Declaration_Or_Function_Call_Error": {
        "patterns": [
            r"cannot have cv-qualifier",
            r"must be a member function",
            r"invalid use of",
            r"cannot call member function",
            r"use of local variable",
            r"parameter packs not expanded with",
            r"not expanded with",
            r"cannot declare",
            r"forbids declaration",
            r"in declaration",
            r"does not name",
            r"qualified-id in declaration before",
            r"uninitialized",
            r"only constructors",
            r"conflicts with a previous declaration",
            r"conflicting declaration",
            r"multiple definition of",
            r"too many initializers",
            r"redefinition of",
            r"redeclaration",
            r"expression list treated as",
            r"redeclared",
            r"previous definition here",
            r"duplicate",
            r"argument given.*expected",
            r"wrong number of template arguments",
            r"forming reference to void",
            r"declared void",
            r"there are no arguments",
            r"passing.*argument",
            r"using.*after ‘class’",
            r"no declaration matches", 
            r"invalid declarator",
            r"use of parameter from", 
        ],
        "description": "Valid syntax but violates C++ language rules on declaring and calling things",
    },

    # usually tied to CMakeLists/Makefile
    "Linker_Error": {
        "patterns": [
            r"undefined reference to",
            r"ld returned.*exit status",
            r"cannot find -l",
            r"unrecognized command-line option",
            r"command line processing: unrecognized option",
            r"hpx::exception_list::~exception_list()", #undefined reference to exceptions
            r"set_exception",
            r"exception_info.hpp",
            r"exception.hpp", 
            r"exception_list",
            r"2.42-GCCcore-13.3.0/bin/ld",
            #common issues with namespaces due to linking errors 
            r"hpx::lcos::make_exceptional",
            r"detail::handle_local_exceptions",
            r"detail::static_partitioner",
        ],
        "description": "Linker errors",
    },

    # runtime err
    "Runtime_Error": {
        "patterns": [
            r"Segmentation fault",
            r"signal.*SIGSEGV",
            r"Aborted",
            r"out of memory",
            r"terminate called after throwing",
            r"Assertion.*failed",
        ],
        "description": "Runtime failures",
    },
    #ideally nothing ehree
    "Other_Compilation": {
        "patterns": [],
        "description": "Other compilation errors not matched above",
    },
}

# ERROR_CATEGORIES = {
#         "Boost_Compatibility": {
#         "patterns": [
#                 r"boost::.*is not a member",
#                 r"boost/.*compatibility",
#                 r"is not a member of .boost::",
#                 r"error.*boost"
#                 r"const boost::*"
#             ],
#             "description": "Boost library compatibility issues",
#         },
#     "Target_Language_Error": {
#         "patterns": [ #issues with construct
#             # C++ syntax errors
#             r"expected primary-expression",
#             r"expected.*before.*token",
#             r"missing.*before",
#             # Legion API used wrong
#             r"has no member named.*",
#             r"has no member named.*create_index_partition",
#             r"DomainPointColoring.*was not declared",
#             r"expected.*before.*token",#colon missing usually
#             r"expected.*before",
#             r".*is not a class, namespace, or enumeration",
#             r"is not a template",
#             r"stray .* in program",
#             r"found .* in nested-name-specifier, expected .*::",
#             r"expected .* at end of input",
#             r"expected .* at end of",
#             r"unterminated",
#             r"not expanded with .*...", #usually incorect parameter pack
#             r"cannot have cv-qualifier",
#             r"invalid use of",
#             r"cannot call member function", #initialize structures that don't have this function 
#             r"use of local variable", #usually from automatic storage form containing function 
            
#         ],
#         "description": "C++ syntax errors beyond declarative issues and Legion API signature misuse",
#     },
#     "Type_Or_Declaration_Error": { #TODO: SPLIT 
#         "patterns": [ #surface-level programming issues not necessarily specific to Legion
#             r"invalid initialization of reference.*from expression of type",
#             r"cannot convert.*to.*",
#             r"does not name a type",
#             r"conflicting declaration",
#             r".* is ambiguous", #call of overloaded type errors 
#             r"multiple definition of",
#             r"redefinition of", 
#             r"redeclaration",
#             r"previous definition here",
#            # r".*no match for.*operator", #incorrect operand types 
#             r"no match for",
#             r"extended character",
#             r"error: conversion from",
#             r"could not convert",
#             r"conflicting declaration"
#             r"no matching function",
#             r"type/value mismatch",
#             r"no matching function",
#             r"invalid types.*for array subscript",
#             r"invalid initialization",
#             r"cannot declare",
#             r"has not been declared",
#             r"duplicate",
#             r"no longer supported",
#             r"forbids declaration",
#             r"wrong number of template arguments",
#             r"invalid conversion", 
#             r"converting function", # to type  
#             r"must be a member function",
#             r"uninitialized",
#             r"only constructors", 
#             r"template argument",
#             r"non-static data member", 
#             r"is not a type", 
#             r"may not appear in this context", #uuslaly incorrect parameter declaration 
#             r"incomplete type", 
#             r"in declaration",
#             r"types may not be defined", 
#             r"is not a class"
            
            
#         ],
#         "description": "Type incompatibility or mismatch (e.g., shared_ptr vs Legion::Future) or improper/ambiguous use of function calls",
#     },
#     "Missing_Include": {
#         "patterns": [
#             r".*was not declared in this scope",
#             r"no type named.*in namespace",
#             r"is not a member of",
#         ],
#         "description": "Undeclared identifiers, missing includes or namespace",
#     },
#     "Linker_Error": {
#         "patterns": [
#             r"undefined reference to",
#             r"ld returned.*exit status",
#             r"cannot find.*lib",
#             r"No such file or directory",
#         ],
#         "description": "Linker/linking errors",
#     },
#     "Runtime_Error": {
#         "patterns": [
#             r"Segmentation fault",
#             r"signal.*SIGSEGV",
#             r"Aborted",
#             r"out of memory",
#             r"core dumped", 
#         ],
#         "description": "Runtime failures (segfault, abort, OOM)",
#     },
#     "Other_Compilation": {
#         "patterns": [
#            # r"error:.*",  # catch-all for compilation errors
#         ],
#         "description": "Other compilation errors not in above categories",
#     },
# }


def extract_error_lines(text: str) -> List[str]:
    """Extract only error lines, ignoring warnings and notes."""
    if not text:
        return []

    lines = text.split('\n')
    errors = []

    for line in lines:
        # Skip warnings, notes, and info
        if re.search(r':\s*(warning|note|info):', line, re.IGNORECASE):
            continue
        # Only keep lines with 'error:' in them or common patterns for how errors are introduced
        if re.search(r':\s*error:', line, re.IGNORECASE):
            errors.append(line.strip())
        if re.search(r'undefined reference to', line, re.IGNORECASE):
            errors.append(line.strip())
        if re.search(r'ld returned.*exit status', line, re.IGNORECASE):
            errors.append(line.strip())
        if re.search(r'cannot find.*lib', line, re.IGNORECASE):
            errors.append(line.strip())
        if re.search(r'Segmentation fault', line, re.IGNORECASE):
            errors.append(line.strip())
            continue
        if re.search(r'signal.*SIGSEGV', line, re.IGNORECASE):
            errors.append(line.strip())
            continue
        if re.search(r'Aborted', line, re.IGNORECASE):
            errors.append(line.strip())
            continue
        if re.search(r'out of memory', line, re.IGNORECASE):
            errors.append(line.strip())
            continue
        if re.search(r'terminate called after throwing', line, re.IGNORECASE):
            errors.append(line.strip())
            continue
        if re.search(r'exception', line, re.IGNORECASE):
            errors.append(line.strip())
            continue
        if re.search(r'fatal error', line, re.IGNORECASE):
            errors.append(line.strip())
            continue
        if re.search(r'runtime error', line, re.IGNORECASE):
            errors.append(line.strip())
            continue
        if re.search(r'assert.*failed', line, re.IGNORECASE):
            errors.append(line.strip())
            continue

    return errors


def categorize_error(error_line: str) -> str:
    """Categorize a single error line based on patterns."""
    for category, config in ERROR_CATEGORIES.items():
        for pattern in config["patterns"]:
            if re.search(pattern, error_line, re.IGNORECASE):
                return category
    return "Other_Compilation"


def parse_results_file(filepath: str) -> List[Dict]:
    """Load JSON results file."""
    try:
        with open(filepath, 'r') as f:
            return json.load(f)
    except Exception as e:
        print(f"ERROR: Could not load {filepath}: {e}")
        return []


def analyze_entry(entry: Dict) -> Dict[str, any]:
    """Analyze a single result entry for errors."""
    app = entry.get("app", "unknown")
    llm = entry.get("llm_name", "unknown")
    dest_model = entry.get("dest_model", "unknown")
    output_num = entry.get("output_number", "?")

    # Collect all error stderr texts (build + code_only build + run)
   # all_stderr_texts = []
    build_stderr_texts = []
    runtime_stderr_texts = []

    # Build errors (both regular and code_only) combined 
    if entry.get("build_stderr"):
        build_stderr_texts.append(("build", entry["build_stderr"]))
    if entry.get("code_only_build_stderr"):
        build_stderr_texts.append(("code_only_build", entry["code_only_build_stderr"]))

    # Run errors (both regular and code_only) combined 
    if entry.get("run_stderrs"):
        for i, stderr in enumerate(entry["run_stderrs"]):
            if stderr:
                runtime_stderr_texts.append((f"run[{i}]", stderr))
    if entry.get("code_only_run_stderrs"):
        for i, stderr in enumerate(entry["code_only_run_stderrs"]):
            if stderr:
                runtime_stderr_texts.append((f"code_only_run[{i}]", stderr))

    build_error_counts = defaultdict(int)
    build_error_messages = defaultdict(list)
    build_error_rows = []

    runtime_error_counts = defaultdict(int)
    runtime_error_messages = defaultdict(list)
    runtime_error_rows = []

    for source, stderr_text in build_stderr_texts:
        error_lines = extract_error_lines(stderr_text)
        for error_line in error_lines:
            category = categorize_error(error_line)
            build_error_counts[category] += 1
            if error_line not in build_error_messages[category]:
                build_error_messages[category].append(error_line)
            build_error_rows.append({
                "output_number": output_num,
                "phase": "build",
                "source": source,
                "error_type": category,
                "error_message": error_line,
                "app": app,
                "llm": llm,
                "dest_model": dest_model,
            })

    for source, stderr_text in runtime_stderr_texts:
        error_lines = extract_error_lines(stderr_text)
        for error_line in error_lines:
            category = categorize_error(error_line)
            runtime_error_counts[category] += 1
            if error_line not in runtime_error_messages[category]:
                runtime_error_messages[category].append(error_line)
            runtime_error_rows.append({
                "output_number": output_num,
                "phase": "runtime",
                "source": source,
                "error_type": category,
                "error_message": error_line,
                "app": app,
                "llm": llm,
                "dest_model": dest_model,
            })

    return {
        "app": app,
        "llm": llm,
        "dest_model": dest_model,
        "output_number": output_num,
        "build_error_counts": dict(build_error_counts),
        "build_error_messages": dict(build_error_messages),
        "build_error_rows": build_error_rows,
        "runtime_error_counts": dict(runtime_error_counts),
        "runtime_error_messages": dict(runtime_error_messages),
        "runtime_error_rows": runtime_error_rows,
        "total_build_errors": sum(build_error_counts.values()),
        "total_runtime_errors": sum(runtime_error_counts.values()),
        "total_errors": sum(build_error_counts.values()) + sum(runtime_error_counts.values()),
    }


def generate_report(analyses: List[Dict], output_file: str):
    """Generate a comprehensive error report."""
    lines = []

    lines.append("=" * 100)
    lines.append("ERROR ANALYSIS REPORT")
    lines.append("=" * 100)
    lines.append("")

    # ── Category descriptions ──
    lines.append("ERROR CATEGORIES:")
    lines.append("─" * 100)
    for category, config in ERROR_CATEGORIES.items():
        lines.append(f"  {category:30} : {config['description']}")
    lines.append("")

    # ── Aggregate statistics ──
    lines.append("AGGREGATE STATISTICS:")
    lines.append("─" * 100)

    total_entries = len(analyses)
    entries_with_errors = sum(1 for a in analyses if a["total_errors"] > 0)
    total_build_error_count = sum(a["total_build_errors"] for  a in analyses)
    total_runtime_error_count = sum(a["total_runtime_errors"] for  a in analyses) 
    total_error_count = total_build_error_count + total_runtime_error_count

    lines.append("AGGREGATE STATISTICS:")
    lines.append("─" * 100)
    lines.append(f"  Total entries analyzed:      {total_entries}")
    lines.append(f"  Entries with errors:         {entries_with_errors}")
    lines.append(f"  Total build errors:          {total_build_error_count}")
    lines.append(f"  Total runtime errors:        {total_runtime_error_count}")
    lines.append(f"  Total error instances:       {total_error_count}")
    lines.append("")
    build_global_counts = defaultdict(int)
    runtime_global_counts = defaultdict(int)
    csv_rows = []

    for analysis in analyses:
        for category, count in analysis["build_error_counts"].items():
            build_global_counts[category] += count
        for category, count in analysis["runtime_error_counts"].items():
            runtime_global_counts[category] += count
        csv_rows.extend(analysis["build_error_rows"])
        csv_rows.extend(analysis["runtime_error_rows"])

    lines.append("BUILD ERROR CATEGORY TOTALS:")
    lines.append("─" * 100)
    for category in sorted(build_global_counts.keys(), key=lambda x: build_global_counts[x], reverse=True):
        count = build_global_counts[category]
        pct = (count / total_build_error_count * 100) if total_build_error_count > 0 else 0
        lines.append(f"  {category:30} : {count:5d}  ({pct:5.1f}%)")
    lines.append("")

    lines.append("RUNTIME ERROR CATEGORY TOTALS:")
    lines.append("─" * 100)
    for category in sorted(runtime_global_counts.keys(), key=lambda x: runtime_global_counts[x], reverse=True):
        count = runtime_global_counts[category]
        pct = (count / total_runtime_error_count * 100) if total_runtime_error_count > 0 else 0
        lines.append(f"  {category:30} : {count:5d}  ({pct:5.1f}%)")
    lines.append("")

    lines.append("=" * 100)
    lines.append("PER-ENTRY ERROR DETAILS")
    lines.append("=" * 100)
    lines.append("")

    analyses_sorted = sorted(analyses, key=lambda x: x["total_errors"], reverse=True)

    for i, analysis in enumerate(analyses_sorted, 1):
        if analysis["total_errors"] == 0:
            continue

        lines.append(f"[{i}] {analysis['app']} | {analysis['llm']} | {analysis['dest_model']} | output-{analysis['output_number']}")
        lines.append(f"    Total build errors:   {analysis['total_build_errors']}")
        lines.append(f"    Total runtime errors: {analysis['total_runtime_errors']}")

        if analysis["build_error_counts"]:
            lines.append("    Build breakdown:")
            for category in sorted(analysis["build_error_counts"].keys(),
                                   key=lambda x: analysis["build_error_counts"][x],
                                   reverse=True):
                count = analysis["build_error_counts"][category]
                lines.append(f"      {category:28} : {count:3d}")

        if analysis["runtime_error_counts"]:
            lines.append("    Runtime breakdown:")
            for category in sorted(analysis["runtime_error_counts"].keys(),
                                   key=lambda x: analysis["runtime_error_counts"][x],
                                   reverse=True):
                count = analysis["runtime_error_counts"][category]
                lines.append(f"      {category:28} : {count:3d}")

        if analysis["build_error_messages"]:
            lines.append("    Sample build error messages:")
            for category in sorted(analysis["build_error_counts"].keys(),
                                   key=lambda x: analysis["build_error_counts"][x],
                                   reverse=True):
                samples = analysis["build_error_messages"].get(category, [])[:2]
                for j, msg in enumerate(samples, 1):
                    truncated = msg[:120] + "..." if len(msg) > 120 else msg
                    lines.append(f"        {category} [{j}]: {truncated}")

        if analysis["runtime_error_messages"]:
            lines.append("    Sample runtime error messages:")
            for category in sorted(analysis["runtime_error_counts"].keys(),
                                   key=lambda x: analysis["runtime_error_counts"][x],
                                   reverse=True):
                samples = analysis["runtime_error_messages"].get(category, [])[:2]
                for j, msg in enumerate(samples, 1):
                    truncated = msg[:120] + "..." if len(msg) > 120 else msg
                    lines.append(f"        {category} [{j}]: {truncated}")

        lines.append("")

    report = "\n".join(lines)

    with open(output_file, 'w') as f:
        f.write(report)

    csv_file = os.path.splitext(output_file)[0] + ".csv"
    with open(csv_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["output_number", "phase", "source", "error_type", "error_message", "app", "llm", "dest_model"]
        )
        writer.writeheader()
        writer.writerows(csv_rows)

    print(f"\n✓ Report saved to {output_file}")
    print(f"✓ CSV saved to {csv_file}")
    print(f"\n{report}")


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <results.json> [output.txt]")
        print(f"  results.json: Path to the validation results JSON file")
        print(f"  output.txt: Path to save the error report (default: error_report.txt)")
        sys.exit(1)

    results_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else "error_report.txt"

    if not os.path.isfile(results_file):
        print(f"ERROR: {results_file} not found")
        sys.exit(1)

    print(f"Loading results from {results_file}...")
    entries = parse_results_file(results_file)

    if not entries:
        print("No entries to analyze.")
        sys.exit(1)

    print(f"Analyzing {len(entries)} entries...")
    analyses = [analyze_entry(entry) for entry in entries]

    print(f"Generating report...")
    generate_report(analyses, output_file)


if __name__ == "__main__":
    main()